"""add_task_table

Revision ID: 9071305b6079
Revises: a2f2679ba5bf
Create Date: 2026-06-25 13:47:13.719820

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '9071305b6079'
down_revision = 'a2f2679ba5bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
        sa.Column('task_id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('milestone_id', sa.Integer(), nullable=False),
        sa.Column('parent_id', sa.Integer(), nullable=True),
        sa.Column('title', sa.NVARCHAR(length=255), nullable=False),
        sa.Column('description', sa.NVARCHAR(), nullable=True),
        sa.Column('status', sa.NVARCHAR(length=50), nullable=False, server_default='Pending'),
        sa.Column('assigned_to', sa.Integer(), nullable=True),
        sa.Column('due_date', sa.Date(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('GETDATE()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['milestone_id'], ['milestone.milestone_id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['parent_id'], ['task.task_id'], ondelete='NO ACTION'),
        sa.ForeignKeyConstraint(['assigned_to'], ['user_account.user_id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index(op.f('ix_task_milestone_id'), 'task', ['milestone_id'], unique=False)
    op.create_index(op.f('ix_task_parent_id'), 'task', ['parent_id'], unique=False)
    op.create_index(op.f('ix_task_status'), 'task', ['status'], unique=False)
    op.create_index(op.f('ix_task_assigned_to'), 'task', ['assigned_to'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_assigned_to'), table_name='task')
    op.drop_index(op.f('ix_task_status'), table_name='task')
    op.drop_index(op.f('ix_task_parent_id'), table_name='task')
    op.drop_index(op.f('ix_task_milestone_id'), table_name='task')
    op.drop_table('task')
    # ### end Alembic commands ###

