"""add_email_log

Revision ID: a2f2679ba5bf
Revises: 4f98a13fde4f
Create Date: 2026-06-22 13:43:00.191204

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = 'a2f2679ba5bf'
down_revision = '4f98a13fde4f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()
    if 'email_log' not in tables:
        op.create_table('email_log',
            sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
            sa.Column('recipients', sa.NVARCHAR(length=500), nullable=False),
            sa.Column('subject', sa.NVARCHAR(length=300), nullable=False),
            sa.Column('event_type', sa.NVARCHAR(length=100), nullable=False),
            sa.Column('status', sa.NVARCHAR(length=20), nullable=False),
            sa.Column('error_msg', sa.NVARCHAR(length=500), nullable=True),
            sa.Column('sent_at', sa.DateTime(), server_default=sa.text('GETDATE()'), nullable=True),
            sa.PrimaryKeyConstraint('log_id')
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()
    
    if 'email_log' in tables:
        op.drop_table('email_log')
    # ### end Alembic commands ###
